apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default  # Use "cert-manager" if deployed in that namespace
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: timilehinolabisi15@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx
