apiVersion: v1
kind: Service
metadata:
  name: dice-service
  labels:
    app: dice
    type: front-end
spec:
  selector:
    app: dice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
