apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soft-ingress
  annotations:  
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - wor;d.timiscodes.xyz
    secretName: world-tls
  rules:
  - host: world.timiscodes.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: soft-service
            port:
              number: 80
