apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify
  labels:
    app: app-spotify
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-spotify
  template:
    metadata:
      labels:
        app: app-spotify
    spec:
      containers:
        - name: spotify-app
          image: linuxserver/your_spotify:1.12.0
          ports:
            - containerPort: 3000
