name: Deploy to Kubernetes

on:
  pull_request:
    branches: 
      - main # Pull request
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull timiscode/web01:latest
      shell: bash

    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t timiscode/web01:latest ./2136_kool_form_pack
    #     docker push timiscode/web01:latest

    - name: Setup kubectl
      run: |
        mkdir -p ~/.kube  # Ensure the directory exists
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
        chmod 600 ~/.kube/config
      shell: bash
    
    - name: Build Deployment & Service
      run: | 
        kubectl create -f  2136_kool_form_pack/deployment.yml
        kubectl create -f  2136_kool_form_pack/service.yml
      shell: bash
      
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/web01 app-web01=timiscode/web01:latest 
        kubectl rollout status deployment/web01
      shell: bash

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f 2136_kool_form_pack/deployment.yml
      shell: bash
      # updated1
     