name: Deploy to Kubernetes

on:
  pull_request:
    branches: 
      - main # Pull request
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Pull Docker Image
    #   run: docker pull timiscode/web01:latest
    #   shell: bash

    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t timiscode/soft:latest ./Soft_Website
    #     docker push timiscode/soft:latest
    #   shell: bash

    - name: Setup kubectl
      run: |
        mkdir -p ~/.kube  # Ensure the directory exists
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
        chmod 600 ~/.kube/config
      shell: bash
    
    - name: Build Deployment & Service
      run: | 
        kubectl delete deployment soft-app
        kubectl delete service soft-service
        kubectl create -f Soft_Website/deployment.yml
        kubectl create -f Soft_Website/service.yml
      shell: bash
      
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/soft-app soft-app=timiscode/soft:latest 
        kubectl rollout status deployment/soft-app
      shell: bash

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f Soft_Website/deployment.yml
      shell: bash
      # updated1

    - name: Describe service & checking port
      run: |
        kubectl apply -f Soft_Website/service.yml
        kubectl describe svc soft-service
        kubectl describe deployment soft-app
      shell: bash
      
    # - name: Create Ingress for deployment
    #   run: kubectl apply -f 2136_kool_form_pack/ingress.yml
    #   shell: bash

    # - name: Create certificate
    #   run: |
    #     kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
    #     kubectl create -f 2136_kool_form_pack/cluster-issuer.yml
    #     kubectl create -f 2136_kool_form_pack/certificate.yml
    #   shell: bash
